version: "3.9"
services:
  postgres:
    image: postgres:14.5-bullseye
    restart: always
    profiles: ["db", "backend", "all"]
    environment:
      # Note: The values here and those in config/sqlg.properties must match
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nixgraph
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  gremlin:
    build:
      context: ./docker/sqlg
      dockerfile: sqlg.Dockerfile
    healthcheck:
      test: /check-status.sh
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    profiles: ["db", "backend", "all"]
    volumes:
      - ./config/sqlg.properties:/secrets/sqlg.properties
      - ./scripts/check-status.sh:/check-status.sh
    ports:
      - 8182:8182
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - gremlin
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: /venv/bin/gunicorn 'explorer.api:app' --workers 4 --worker-class
      uvicorn.workers.UvicornWorker --bind '0.0.0.0:5000'
    profiles: ["backend", "all"]
    ports:
      - 5000:5000
    env_file:
      - ./api/.env.prod
    depends_on:
      gremlin:
        condition: service_healthy
    networks:
      - backend
  web:
    build: ./web
    environment:
      - API_URL=api:5000
    profiles: ["frontend", "all"]
    ports:
      - 9091:80
    depends_on:
      - api
    networks:
      - backend
volumes:
  pg_data: {}
networks:
  backend:
