version: "3.9"
services:
  postgres:
    image: postgres:14.5-bullseye
    restart: always
    environment:
      # Note: The values here and those in config/sqlg.properties must match
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nixgraph
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  gremlin:
    build:
      context: ./docker/sqlg
      dockerfile: sqlg.Dockerfile
    restart: always
    volumes:
      - ./config/sqlg.properties:/config/sqlg.properties
    ports:
      - 8182:8182
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - gremlin
  api:
    build: ./api
    command:
      /venv/bin/gunicorn 'explorer:app' --workers 4 --worker-class
      uvicorn.workers.UvicornWorker --bind '0.0.0.0:5000'
    ports:
      - 5000:5000
    env_file:
      - ./api/.env.dev
    depends_on:
      - gremlin
    networks:
      - backend
  web:
    build: ./web
    ports:
      - 9091:80
    depends_on:
      - api
    networks:
      - backend
volumes:
  pg_data: {}
networks:
  backend:
