version: "3.9"
services:
  postgres:
    image: postgres:14.5-bullseye
    restart: always
    environment:
      # Note: The values here and those in config/sqlg.properties must match
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nixgraph
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  gremlin:
    build:
      context: .
      dockerfile: sqlg.Dockerfile
    restart: always
    volumes:
      - ./config/sqlg.properties:/config/sqlg.properties
    ports:
      - 8182:8182
    depends_on:
      - postgres
volumes:
  pg_data: {}
